name: Frescobaldi release
# This action is intended to be run on releases, but the
# manual trigger (workflow_dispatch) might be useful
# to test the packages before a release.
on:
  workflow_dispatch:
  release:
    types: [published]

env:
  FORCE_COLOR: "1"

defaults:
  run:
    shell: bash

jobs:
  tarball:
    # Tarball including .mo files plus the built .desktop and .metainfo.xml files
    name: Make a tarball for Linux packagers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install python dependencies
        run: python -m pip install --upgrade pip wheel tox
      - name: Build tarball
        id: build_tarball
        run: |
          tox -e mo-generate
          tox -e linux-generate
          tox -e linux-validate
          python -m build
          echo "filename=$(ls dist/*.tar.gz)" >> "$GITHUB_OUTPUT"
      - name: Tarball upload
        if: github.event.release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ${{ steps.build_tarball.outputs.filename }}
          tag: ${{ github.ref }}

  packages:
    name: Make packages for Windows and macOS
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        target: ["Windows"]
        include:
          - target: "Windows"
            platform: "windows"
            output-format: "app"
            runs-on: "windows-latest"
            filename: dist/*.msi

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Windows dependencies
        if: matrix.target == 'Windows'
        shell: pwsh
        run: |
          iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
          scoop install main/gettext

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install briefcase tox

      - name: Build Frescobaldi translations on Windows
        if: matrix.target == 'Windows'
        run: |
          export PATH=/c/Users/runneradmin/scoop/shims:$PATH
          tox -e mo-generate

      - name: Build Frescobaldi
        run: |
          ${{ matrix.briefcase-build-prefix }} \
          briefcase build \
            ${{ matrix.platform || matrix.target }} \
            ${{ matrix.output-format }} \
            --test --no-input --log \
            ${{ matrix.briefcase-args }} \
            ${{ matrix.briefcase-build-args }}

      - name: Package Frescobaldi
        run: |
          ${{ matrix.briefcase-package-prefix }} \
          briefcase package \
            ${{ matrix.platform || matrix.target }} \
            ${{ matrix.output-format }} \
            --update --no-input --log \
            ${{ matrix.briefcase-args }} \
            ${{ matrix.briefcase-package-args }}

      - name: Upload Frescobaldi
        uses: actions/upload-artifact@v4
        with:
          name: frescobaldi-${{ matrix.target }}
          path: dist
          if-no-files-found: error

      - name: Upload Log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Log-Failure-${{ matrix.target }}
          path: logs/*

      - name: Release upload
        if: github.event.release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ${{ matrix.filename }}
          tag: ${{ github.ref }}

